//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LoginTask
{
    using System;
    using System.Collections.Generic;
    
    public partial class DailyTask1
    {
        public int Id { get; set; }
        public int SubTopicId { get; set; }
        public System.DateTime StartTime { get; set; }
        public System.DateTime EndTime { get; set; }
        public int EstimatedHr { get; set; }
    
        public virtual SubTopic SubTopic { get; set; }
    }
}
