//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LoginTask
{
    using System;
    using System.Collections.Generic;
    
    public partial class SubTopic
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SubTopic()
        {
            this.DailyTask1 = new HashSet<DailyTask1>();
        }
    
        public int Id { get; set; }
        public string SubTopicName { get; set; }
        public int TopicId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DailyTask1> DailyTask1 { get; set; }
        public virtual Topic Topic { get; set; }
    }
}
